// 추후에는 리버스 프록시 서버를 두어 해결하길 바람
pipeline {
    agent any

    environment {
        OS = 'debian'
        NODE_VERSION = '20'
        NPM_TOKEN = credentials('npm_token_momojslife')
        GITHUB_TOKEN = credentials('github_token')
    }

    triggers {
        githubPush()
    }

    options {
        // timeout
        timeout(time: 15, unit: "MINUTES")
        // 동시 빌드 방지
        disableConcurrentBuilds()
        // 빌드 history 유지
        // buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    stages {
        stage('Deploy module to NPM') {
            when {
                allOf {
                    anyOf {
                        branch 'main'
                        branch 'dev'
                    }
                    expression { env.CHANGE_ID != null }
                }
            }

            tools {
                nodejs "node ${NODE_VERSION}"
            }

            stages {
                stage('Setup') {
                    steps {
                        // git checkout
                        checkout scm

                        echo "Processing Pull Request #${env.CHANGE_ID}"
                        echo "Source Branch: ${env.CHANGE_BRANCH}"
                        echo "Target Branch: ${env.CHANGE_TARGET}"

                        // Git 설정
                        sh '''
                            git config user.name 'Jenkins Bot'
                            git config user.email 'jenkins@example.com'
                        '''

                        // NPM 설정
                        sh '''
                            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
                        '''
                    }
                }

                stage('Branch Check') {
                    steps {
                        script {
                            def currentBranch = sh(script: 'git rev-parse --abbrev-ref HEAD', returnStdout: true).trim()
                            if (currentBranch != 'main' && currentBranch != 'master') {
                                error "main/master 브랜치만 허용됩니다"
                            }
                        }
                    }
                }

                stage('Install Dependancies') {
                    steps {
                        // npm-run-all 설치
                        sh '''
                            npm i --save-dev npm-run-all
                        '''
                        // Lerna 부트스트랩
                        sh 'npx lerna bootstrap --ci'
                    }
                }
                
                stage('Build & Test') {
                    // TODO: 검증 과정 필요할 듯.. (npm run lint, run test...)
                    steps {
                        sh 'npm run sync && npx lerna run build'
                    }
                }

                stage('Publish') {
                    steps {
                        sh '''
                            npx lerna version -y
                            npx lerna publish -y
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            sh 'rm -f .npmrc'

            cleanWs()
        }
    }
}